# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        node-version:
        - 22
        - 20
        - 18
        - 16
        - 14
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        
    - name: Install dependencies with npm or pnpm
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        elif [ -f pnpm-lock.yaml ]; then
          npm install -g pnpm
          pnpm install --frozen-lockfile
        else
          echo "No lock file found. Please add a package-lock.json or pnpm-lock.yaml file."
          exit 1
        fi
        
    - name: Build and Test
      run: |
        if [ -f package-lock.json ]; then
          npm run build --if-present
          npm test
        elif [ -f pnpm-lock.yaml ]; then
          pnpm run build --if-present
          pnpm test
        else
          echo "Lock file not found. Cannot run build or test scripts."
          exit 1
        fi
